Add comments to crucial functions.
git-svn-id: https://nemerle.googlecode.com/svn/nemerle/trunk@673 c8a6711f-211a-0410-a8d5-2f220496d6d1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -91,6 +91,19 @@ echo_result () {
 }
 
 
+# This function tries to execute command given as an argument and returns
+# shell exit code.  If the program doesn't exist in a path shell returns
+# 127.  If the program is not a valid executable shell returns 126.
+# If the program lacks some arguments it usually returns 1, otherwise
+# this function should return 0.
+#
+# E.g.
+# try_execute cc --version
+# if test $? = 0; then
+#    echo "found"
+# else
+#    echo "not found"
+# fi
 try_execute () {
 
     echo "Trying execute: $@" >> $config_log
@@ -101,6 +114,9 @@ try_execute () {
 }
 
 
+# This function assumes that it is given a list of programs, that should be
+# run one after another.  Then result holds name of the program that
+# succeeded or nothing.
 check_csc () {
 
     found=0
@@ -398,28 +414,31 @@ done
 
 
 echo_check_for "xspp"
-if try_execute xspp; then
-    echo_result no
-else
+try_execute xspp
+if test $? -lt 126; then
     echo_result yes
+else
+    echo_result no
 fi
 xspp=xspp
 
 
 echo_check_for "xsltproc"
-if try_execute xsltproc --version; then
-    echo_result no
-else
+try_execute xsltproc --version
+if test $? -lt 126; then
     echo_result yes
+else
+    echo_result no
 fi
 xsltproc=xsltproc
 
 
 echo_check_for "xmllint"
-if try_execute xmllint --version; then
-    echo_result no
-else
+try_execute xmllint --version
+if test $? -lt 126; then
     echo_result yes
+else
+    echo_result no
 fi
 xmllint=xmllint
 
