Add --ignore-errors option to configure.
git-svn-id: https://nemerle.googlecode.com/svn/nemerle/trunk@1520 c8a6711f-211a-0410-a8d5-2f220496d6d1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -50,6 +50,7 @@ nem_tmp_file=
 nem_flags=
 time=
 quiet=@
+ignore_errors=no
 
 force_old=0
 
@@ -66,9 +67,13 @@ abort () {
 	echo "*** Check $config_log for details. ***"
     fi
     echo
-    echo "Aborting..."
-    rm -f $config_mak
-    exit 1
+    if [ "$ignore_errors" = yes ] ; then
+      echo "*** Ignoring error. ***"
+    else
+      echo "Aborting..."
+      rm -f $config_mak
+      exit 1
+    fi
 }
 
 echo_check_for () {
@@ -167,6 +172,7 @@ Miscellaneous options:
   --force-old-mono      use this switch to force using your version of
                         Mono .NET environment or if you don't use Mono
                         at all but have it installed
+  --ignore-errors       do not exit on errors
 
 Optional features:
   --enable-debug        adds --debug to net-flags
@@ -225,6 +231,9 @@ for ac_option do
 	    ;;
         --disable-quiet)
 	    quiet=
+	    ;;
+	--ignore-errors)
+	    ignore_errors=yes
 	    ;;
 	*)
 	    echo "Unknown parameter: $ac_option"
