Check for mono i8 problems and propose workaround.
git-svn-id: https://nemerle.googlecode.com/svn/nemerle/trunk@4838 c8a6711f-211a-0410-a8d5-2f220496d6d1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -401,6 +401,19 @@ else
 	echo_result "no"
 fi
 
+echo_check_if "i8 arithmetics works"
+chmod +x boot/testcompat.exe
+if try_execute $engine boot/testcompat.exe ; then
+  echo_result "ok"
+else
+  echo_result "problems"
+  echo "*** If you are using mono on amd64, you either need SVN version ***"
+  echo "*** or 1.1.6 with this patch: ***"
+  echo "    http://lists.ximian.com/archives/public/mono-patches/2005-April/057097.html"
+  echo "*** Cannot continue. ***"
+  exit 1
+fi
+
 # Step 3a.
 # Check if there is regtool.exe available in the system and configure paths
 # to .NET SDK and Framework according to choosen version
