Add antlr dll
git-svn-id: https://nemerle.googlecode.com/svn/nemerle/trunk@3536 c8a6711f-211a-0410-a8d5-2f220496d6d1

diff --git a/tools/cs2n/configure b/tools/cs2n/configure
--- a/tools/cs2n/configure
+++ b/tools/cs2n/configure
@@ -36,8 +36,7 @@ result=
 config_log="configure.log"
 
 javavm=0
-antlr=
-classpath=
+antlr=0
 
 ############################################################
 # FUNCTIONS
@@ -116,64 +115,49 @@ if test "$?" = 0; then
 fi 
 
 # STEP 2
-# Require that ANTLR_HOME is specified
-echo_check_if "ANTLR_HOME is specified"
-if [ "$ANTLR_HOME" = "" ] ;  then
-	echo_result "no"
-	echo "*** No ANTLR_HOME specified ***"
-	abort "See README for details"
-else
-    echo_result "yes"
-fi
-
-# STEP 3
 # Check for Antlr >= 2.7
 if test "$javavm" = 1  ; then
     echo_check_for "antlr >= 2.7"
     classpath="$ANTLR_HOME/antlr.jar"
-    ver=`java -classpath  $classpath antlr.Tool 2>&1| head -1 | sed 's/.* \([0-9]*\.[0-9]\.[0-9]*\).*/\1/g'`
+    ver=`antlr 2>&1| head -1 | sed 's/.* \([0-9]*\.[0-9]\.[0-9]*\).*/\1/g'`
     case $ver in  
 	2.7*) 
+	    antlr=1
 	    echo_result "yes" 
 	    ;; 	
 	2.8*) 
-	    echo_result "yes" 
-	    ;; 
-	2.9*) 
-	    echo_result "yes" 
-	    ;; 
-	3*) 
+	    antlr=1
 	    echo_result "yes" 
 		;; 
 	*) 
 	    echo_result "no" 
-	    echo "*** You probably have too old version of antlr ***"
-	    abort "Too old version of antlr" 
+	    abort "antlr > = 2.7 not installed "	    
 	    ;; 
     esac 
 fi
 
+echo 
+echo "Type 'make' to compile cs2n"
 # STEP 4
 # Check if antlr.runtime.dll exists
-echo_check_if "antlr.runtime.dll exists in $ANTLR_HOME/lib/csharp/src"
-ex=`ls $ANTLR_HOME/lib/csharp/src/antlr.runtime.dll 2> /dev/null`
-if test "$?" = 0 ; then
-    echo_result "yes"
-else
-    echo "*** antlr.runtime.dll should be in $ANTLR_HOME/lib/csharp/src ***"
-    abort "antlr.runtime.dll missing"
-    echo_result "no"
-fi
+# echo_check_if "antlr.runtime.dll exists in $ANTLR_HOME/lib/csharp/src"
+# ex=`ls $ANTLR_HOME/lib/csharp/src/antlr.runtime.dll 2> /dev/null`
+# if test "$?" = 0 ; then
+#    echo_result "yes"
+# else
+#    echo "*** antlr.runtime.dll should be in $ANTLR_HOME/lib/csharp/src ***"
+#    abort "antlr.runtime.dll missing"
+#    echo_result "no"
+# fi
 
 # STEP 5
 # Creating config.cs2n.mak
 
-echo "Creating config.cs2n.mak"
+# echo "Creating config.cs2n.mak"
 
-cat > config.cs2n.mak <<EOF
-# Generated by configure
+# cat > config.cs2n.mak <<EOF
+# # Generated by configure
 
-antlrhome = $ANTLR_HOME
-classpath = $classpath
+# antlr = $antlr
 
-EOF
+# EOF
